# -*- coding: utf-8 -*-
"""test02.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nWWOgWr0tTQkoGtBzC9lizpn9Wv1u6CP
"""

import math


def sin(x):
    if 2 * x == pi:
        return 0.99999999
    else:
        return None


pi = 3.14

print(sin(pi/2))
print(math.sin(math.pi/2))

from math import pi

print(math.e)

from math import sin, pi

print(sin(pi/2))

pi = 3.14


def sin(x):
    if 2 * x == pi:
        return 0.99999999
    else:
        return None


print(sin(pi / 2))

from math import sin, pi

print(sin(pi / 2))

if True:
  print("True")

def funcion(a, b, c):
    return a+b+c

d = funcion(10,
23,
3)

print(d)

import keyword
print(keyword.kwlist)



x = 10

def funcion():
    x = 5

funcion()
print(x)

x= [10, 20, 30]
def funcion (entrada):
    entrada.append(40)
funcion(x)
print(x) #[10, 20, 30]

x = 10
print(id(x)) # 4349704528
def funcion(entrada):
    entrada = 0
    print(id(entrada)) # 4349704208

funcion(x)

x = [10, 20, 30]
print(id(x)) # 4422423560
def funcion(entrada):
    entrada.append(40)
    print(id(entrada)) # 4422423560

funcion(x)